#!/usr/bin/env bash
# vault-quality-gates — the `init` extension point.
#
# The vault framework runs this during bin/vault-init.sh, after VAULT.md exists, through this
# shebang in a child process with stdin closed. Arguments: <code-repo> <vault-dir> <slug>.
#
# It leaves the target repo able to answer, without reading anything in this repo:
#   - what this plugin is and where it is installed
#   - the nine columns of quality/checks.tsv and every legal value
#   - which parsers actually ship, listed from lib/guard-parsers/ so the list cannot drift
#   - the exact next step
#
# That last point is the whole job. A scaffold that writes a config file and no instructions makes
# the next session design the system from a header comment.
#
# Exit 0 on every path. Running twice changes nothing the second time.

set -u

PLUGIN_NAME="vault-quality-gates"
RELEASE_PATTERN_DEFAULT="refs/heads/release/*"
MARK_START="<!-- ${PLUGIN_NAME}:start — regenerated by extend/init.sh; edit outside this block -->"
MARK_END="<!-- ${PLUGIN_NAME}:end -->"

# Resolved at run time, so the path written into the target repo is always the real install.
PLUGIN_ROOT=$(cd "$(dirname "$0")/.." 2>/dev/null && pwd) || exit 1

code_repo=${1:-}
[ -n "${code_repo}" ] || exit 0

vault_md="${code_repo}/VAULT.md"
[ -f "${vault_md}" ] || exit 0

mkdir -p "${code_repo}/quality" || exit 1

# --- what ships, read from disk rather than restated ---------------------------------------

parsers=""
for f in "${PLUGIN_ROOT}"/lib/guard-parsers/*.sh; do
    [ -f "$f" ] || continue
    b=$(basename "$f" .sh)
    case "$b" in _*) continue ;; esac
    parsers="${parsers}${parsers:+, }\`${b}\`"
done
[ -n "${parsers}" ] || parsers="none — \`${PLUGIN_ROOT}/lib/guard-parsers/\` is empty"

runner_state="present"
[ -x "${PLUGIN_ROOT}/bin/guard.sh" ] || runner_state="NOT BUILT — \`${PLUGIN_ROOT}/bin/guard.sh\` does not exist yet"

# --- quality/checks.tsv --------------------------------------------------------------------
#
# Header only. Rows are per stack and per repo; a guessed row gates a push on a tool nobody chose.

checks="${code_repo}/quality/checks.tsv"
if [ ! -f "${checks}" ]; then
    {
        printf 'id\tscope\tkind\tcommand\tparser\tartifact\tdirection\tthreshold\tgate\n'
        printf '# READ quality/README.md IN THIS REPO FIRST. It carries every column, every legal\n'
        printf '# value, the parsers that ship, and the next step. Do not infer them from this file.\n'
        printf '# Empty cells are written `-`, never left blank. No cell may contain a tab.\n'
        printf '# No rows yet. Each row is added only after its command has been run once and its\n'
        printf '# artifact read, because a row that was never run gates a push on a guess.\n'
    } > "${checks}" || exit 1
fi

# --- quality/README.md: the brief the next session actually reads ---------------------------

readme="${code_repo}/quality/README.md"
block=$(cat <<EOF
${MARK_START}

# Quality gates — this repo

This repo is wired to **${PLUGIN_NAME}**, installed at:

\`\`\`
${PLUGIN_ROOT}
\`\`\`

It refuses a \`git push\` to a release branch when a measured metric is worse than the baseline
committed in \`quality/baseline.tsv\`. Every other push is untouched.

**Runner:** ${runner_state}

**Exit codes, everywhere:** 0 measured and acceptable · 1 measured and worse · 2 could not measure.
A check that could not run is never recorded as passing.

## Start here

1. Read \`${PLUGIN_ROOT}/vault/architecture/guard-file-formats.md\` — the full contract.
2. Work out which tools this repo already has. Read its \`composer.json\`, \`package.json\`,
   \`Makefile\` or \`pubspec.yaml\` for commands that already exist. Prefer them over new ones.
3. **Run each command once before you write its row.** Capture the artifact it leaves. A row whose
   command was never run gates a push on a guess.
4. Add the row to \`quality/checks.tsv\`. Then measure the baseline and commit
   \`quality/baseline.tsv\`.

## quality/checks.tsv — nine columns, tab separated

Line 1 is the literal header. A row whose field count differs is refused, not parsed.

| column | legal values | meaning |
|---|---|---|
| \`id\` | \`^[a-z][a-z0-9-]*\$\`, unique | the metric name in the report and the baseline |
| \`scope\` | \`commit\` · \`release\` · \`both\` · \`baseline\` · \`-\` | which run measures it; \`baseline\` is never run by a hook |
| \`kind\` | \`repo\` · \`diff\` · \`absent\` | \`repo\` compares to the baseline; \`diff\` to \`threshold\` as an absolute floor; \`absent\` runs nothing |
| \`command\` | shell, or \`-\` | \`{{base}}\` is the base ref; \`{{files}}\` the changed paths, NUL separated — consume with \`xargs -0\` |
| \`parser\` | a name below, or \`-\` | \`-\` means the command's own stdout is the number |
| \`artifact\` | a path, \`-\`, or the reason when \`kind\` is \`absent\` | what the parser reads |
| \`direction\` | \`up\` · \`down\` · \`-\` | \`up\` when higher is better |
| \`threshold\` | a number, or \`-\` | \`kind: repo\` → worsening tolerated; \`kind: diff\` → the absolute floor or ceiling |
| \`gate\` | \`refuse\` · \`warn\` · \`record\` · \`-\` | \`refuse\` exits 1; \`warn\` records and passes; \`record\` stores the number only |

**Parsers that ship:** ${parsers}

Each reads one artifact and prints one number. Their source is
\`${PLUGIN_ROOT}/lib/guard-parsers/\` — read the one you plan to use before writing its row.

**Why \`kind: diff\` never compares to a baseline:** each release push measures a different set of
changed lines, so two scores describe different populations.

## quality/baseline.tsv — the ratchet

Four columns: \`id\`, \`value\`, \`commit\`, \`reason\`. Only \`kind: repo\` ids appear. Committed, so
the ratchet travels with the branch and is visible in review.

## Two rules that bite

1. **Nothing whole-repo runs at push time.** A suite that takes an hour makes the gate unusable and
   it gets bypassed. Slow measurements carry \`scope: baseline\` and run out of band.
2. **A tool that fails is not a tool that passed.** Exit 2 refuses. Never record a null as a pass.

${MARK_END}
EOF
)

if [ ! -f "${readme}" ]; then
    printf '%s\n' "${block}" > "${readme}" || exit 1
elif grep -qF "${MARK_START}" "${readme}"; then
    # Regenerate only the delimited block, so anything the operator wrote around it survives.
    tmp=$(mktemp) || exit 1
    awk -v s="${MARK_START}" -v e="${MARK_END}" -v repl="${block}" '
        index($0, s) { print repl; skip = 1; next }
        index($0, e) { skip = 0; next }
        !skip { print }
    ' "${readme}" > "${tmp}" && mv "${tmp}" "${readme}" || { rm -f "${tmp}"; exit 1; }
else
    printf '\n%s\n' "${block}" >> "${readme}" || exit 1
fi

# --- CLAUDE.md: the file a session reads without being told ---------------------------------

claude_md="${code_repo}/CLAUDE.md"
if [ -f "${claude_md}" ] && ! grep -q "${PLUGIN_NAME}" "${claude_md}"; then
    [ -n "$(tail -c1 "${claude_md}")" ] && printf '\n' >> "${claude_md}"
    cat >> "${claude_md}" <<EOF

## Quality gates

This repo is wired to the \`${PLUGIN_NAME}\` plugin: a push to a release branch is refused when a
measured metric is worse than \`quality/baseline.tsv\`.

**Read \`quality/README.md\` before touching \`quality/checks.tsv\`.** It carries the nine columns,
the parsers that ship, and the rule that a row is written only after its command has been run once.
EOF
fi

# --- merge into the plugins scalar ----------------------------------------------------------

[ -n "$(tail -c1 "${vault_md}")" ] && printf '\n' >> "${vault_md}"

if [ "$(grep -c '^plugins:' "${vault_md}")" -gt 1 ]; then
    printf '  %s: VAULT.md has more than one plugins: line — writing nothing\n' "${PLUGIN_NAME}" >&2
    exit 1
fi

current=$(sed -n 's/^plugins:[[:space:]]*//p' "${vault_md}" | head -1 | tr -d '\r')

if ! grep -q '^plugins:' "${vault_md}"; then
    printf 'plugins: %s\n' "${PLUGIN_NAME}" >> "${vault_md}"
elif [ -z "${current}" ]; then
    sed -i "s|^plugins:.*|plugins: ${PLUGIN_NAME}|" "${vault_md}"
elif printf '%s' "${current}" | tr ',' '\n' | tr -d '[:space:]' | grep -qx "${PLUGIN_NAME}"; then
    :
else
    sed -i "s|^\(plugins:.*\)$|\1, ${PLUGIN_NAME}|" "${vault_md}"
fi

# --- every key extend/dod-keys.tsv declares -------------------------------------------------

grep -q '^guard_release_pattern:' "${vault_md}" \
    || printf 'guard_release_pattern: %s\n' "${RELEASE_PATTERN_DEFAULT}" >> "${vault_md}"

printf '  %s: wrote quality/README.md — read it before quality/checks.tsv\n' "${PLUGIN_NAME}"
exit 0
